name: syed_enterprise_pos
version: 1.0.0+4
publish_to: none
description: pos app
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  fluttertoast: ^8.1.2
  flutter_svg: ^1.1.6
  google_fonts: ^3.0.1
  logger: ^1.1.0
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  get_storage: ^2.0.3
  cloud_firestore: ^4.3.1
  intl: ^0.17.0
  connectivity_plus: ^3.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/dashboard/
