// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVVhZAN0dpp79MaUt6hs3aWI3T98ceNf8',
    appId: '1:1016948472066:web:0e75c2b1bdb52f5e0faa1b',
    messagingSenderId: '1016948472066',
    projectId: 'syed-enterprise-pos',
    authDomain: 'syed-enterprise-pos.firebaseapp.com',
    storageBucket: 'syed-enterprise-pos.appspot.com',
    measurementId: 'G-LCEHGGDH4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfmQy4ELJqbVNNGox213RPz5EYYFb80lw',
    appId: '1:1016948472066:android:a455dff8d239a7090faa1b',
    messagingSenderId: '1016948472066',
    projectId: 'syed-enterprise-pos',
    storageBucket: 'syed-enterprise-pos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW6sqcEipL82e2ufLnMxlySf7mVPEmDs0',
    appId: '1:1016948472066:ios:71dd2ba42936bec70faa1b',
    messagingSenderId: '1016948472066',
    projectId: 'syed-enterprise-pos',
    storageBucket: 'syed-enterprise-pos.appspot.com',
    iosClientId:
        '1016948472066-6stnfc5od31l59rtug3djva6j9j6nt3k.apps.googleusercontent.com',
    iosBundleId: 'com.ekotalab.syedEnterprisePos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW6sqcEipL82e2ufLnMxlySf7mVPEmDs0',
    appId: '1:1016948472066:ios:71dd2ba42936bec70faa1b',
    messagingSenderId: '1016948472066',
    projectId: 'syed-enterprise-pos',
    storageBucket: 'syed-enterprise-pos.appspot.com',
    iosClientId:
        '1016948472066-6stnfc5od31l59rtug3djva6j9j6nt3k.apps.googleusercontent.com',
    iosBundleId: 'com.ekotalab.syedEnterprisePos',
  );
}
